CREATE TABLE IF NOT EXISTS public.saved_events (
    id bigint primary key generated by default as identity,
    user_id uuid,
    event_id uuid REFERENCES public.events (id) ON DELETE CASCADE
);

-- Optional: If user_id should also be a foreign key, you can uncomment the following:
-- ALTER TABLE public.saved_events ADD CONSTRAINT saved_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles (id) ON DELETE CASCADE;
