CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint primary key generated by default as identity,
    user_id uuid,
    event_id uuid,
    type varchar,
    message text,
    is_read boolean default false,
    created_at timestamp default now()
);

-- Optional: foreign key constraints
-- ALTER TABLE public.notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles (id) ON DELETE CASCADE;
-- ALTER TABLE public.notifications ADD CONSTRAINT notifications_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events (id) ON DELETE CASCADE;
