-- ====================================================================
-- Migration: Friendship Constraints & Notifications Link
-- ====================================================================

-- 1. Ensure `friend_requests` table exists and matches ERD schema
CREATE TABLE IF NOT EXISTS friend_requests (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    initiator_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    receiver_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    status VARCHAR NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Set default and status validation for friend_requests
ALTER TABLE friend_requests 
    ALTER COLUMN status SET DEFAULT 'pending';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'friend_requests_status_check'
    ) THEN
        ALTER TABLE friend_requests 
            ADD CONSTRAINT friend_requests_status_check 
            CHECK (status IN ('pending', 'accepted', 'declined', 'cancelled'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'friend_requests_no_self'
    ) THEN
        ALTER TABLE friend_requests 
            ADD CONSTRAINT friend_requests_no_self 
            CHECK (initiator_id != receiver_id);
    END IF;
END;
$$;

-- Prevent two pending friend requests between the same two users in EITHER direction
CREATE UNIQUE INDEX IF NOT EXISTS unique_pending_friend_request
ON friend_requests (LEAST(initiator_id, receiver_id), GREATEST(initiator_id, receiver_id))
WHERE status = 'pending';

-- Index for receiver lookup
CREATE INDEX IF NOT EXISTS idx_friend_requests_receiver 
ON friend_requests (receiver_id, status);


-- 2. Ensure `friendships` table exists and matches ERD schema
CREATE TABLE IF NOT EXISTS friendships (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    friend_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    status VARCHAR DEFAULT 'active',
    origin UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'friendships_no_self'
    ) THEN
        ALTER TABLE friendships 
            ADD CONSTRAINT friendships_no_self 
            CHECK (user_id != friend_id);
    END IF;
END;
$$;

-- Prevent the same friendship from being stored twice (in either direction)
CREATE UNIQUE INDEX IF NOT EXISTS unique_friendship_pair
ON friendships (LEAST(user_id, friend_id), GREATEST(user_id, friend_id));

-- Indexes so friendships can be found starting from either user
CREATE INDEX IF NOT EXISTS idx_friendships_user_id ON friendships (user_id);
CREATE INDEX IF NOT EXISTS idx_friendships_friend_id ON friendships (friend_id);


-- 3. Update `notifications` table to point to a user and friend request
ALTER TABLE notifications 
    ADD COLUMN IF NOT EXISTS actor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    ADD COLUMN IF NOT EXISTS friend_request_id BIGINT REFERENCES friend_requests(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_notifications_friend_request_id 
ON notifications (friend_request_id);

CREATE INDEX IF NOT EXISTS idx_notifications_actor_id 
ON notifications (actor_id);
